/* GENERATED by decomp/scripts/gen_ph_rom.py, kept as source. ROM data of the klsyn side of speech. */
#ifndef PH_ROM_H
#define PH_ROM_H
#include <stddef.h>
#include <stdint.h>

#define NPH 56                         /* phonemes 0-55 */
typedef struct { const char *name; int8_t kind; int16_t min, max; const char *desc; } dv_param_t;
typedef struct { int16_t locus, pct_q14, durtran; } ph_locus_t;   /* setloc: a locus rule for one formant */

extern const int16_t sung_vibrato_steps[4]; /* 0x1616a: vibrato steps added to sung F0 */
extern const int16_t notetab[37]; /* 0x16172: sung notes 1-37 (C2-C5), F0 in tenths of Hz (dapi notetab) */
extern const int16_t featb[106]; /* 0x161fe: feature bits per symbol (dapi featb; bits in ph_timing.c) */
extern const int16_t inhdr[NPH]; /* 0x162d2: inherent duration per phoneme, frames */
extern const int16_t mindur[NPH]; /* 0x16342: minimum duration per phoneme, frames */
extern const int16_t f0segtars[NPH]; /* 0x169c4: segmental F0 perturbation per phoneme */
extern const int16_t burst_place[NPH]; /* 0x16a34: per-phoneme rank compared for stop bursts [I] */
extern const int16_t begtyp[NPH]; /* 0x16aa4: transition type at phoneme onset (1-5) */
extern const int16_t endtyp[NPH]; /* 0x16b14: transition type at phoneme offset (1-5) */
extern const int16_t stop_burst_dur[11]; /* 0x16d50: burst duration of phonemes 45-55, frames */
extern const int16_t vot_frames[4]; /* 0x16d66: VOT 6/4/2 frames and the +3 for aspirated onsets */
extern const int16_t reset_tarend[3]; /* 0x16d6e: initial F1-F3 end targets */
extern const int16_t maldip[450]; /* 0x17186: male diphthong lines {value, time}... -1, addressed by -target */
extern const int16_t femdip[450]; /* 0x17ea2: female diphthong lines */
extern const int16_t maltar[7][NPH]; /* 0x163b2: male targets */
extern const int16_t femtar[7][NPH]; /* 0x1750a: female targets */
extern const int16_t burst_amp_set[NPH]; /* 0x16b84: burst amplitude set per phoneme, 1-16 (0 = none); the ROM holds the offset 1 + 24 (set - 1) */
extern const int16_t malamp[16][4][6]; /* 0x166c2: male burst amplitudes [set - 1][type - 1][A2..AB] */
extern const int16_t femamp[16][4][6]; /* 0x1781a: female burst amplitudes [set - 1][type - 1][A2..AB] */
extern const int16_t plocu[3][NPH]; /* 0x16bf4: locus set per (type - 1, phoneme), 0 = none */
extern const ph_locus_t maleloc[50][3]; /* 0x16e00: male locus sets [set - 1][F1..F3] */
extern const ph_locus_t femloc[50][3]; /* 0x17b1c: female locus sets [set - 1][F1..F3] */
extern const int16_t divtab_ext[20 + 50]; /* 0x16d74: divtab (0x16d9c, 16384/n for n frames, dapi divtab) and the 20 ROM words before it, which divtab[-1] ... divtab[-20] read: fnz_default, 11 unreferenced words, partyp as shorts */
#define divtab (divtab_ext + 20)           /* 0x16d9c; divtab[-20..-1] are valid, as on the 68000 */
extern const int16_t fnz_default; /* 0x16d74: the nasal zero at rest, Hz */
extern const int8_t partyp[16]; /* 0x16d8c */
extern const int16_t f2max_by_sex[2];
extern const int16_t f3max_by_sex[2];
extern const int16_t f0_stress_steps[13]; /* 0x15f00: [n] by stressed-syllable count, [5 + s] by stress level */
extern const int16_t bndval[9]; /* 0x15eee: boundary strength of symbols 61-69 */
extern const int16_t voice_defs[8][28]; /* 0x16146: the built-in voice records (voice_t layout) */
extern const dv_param_t dv_param_table[]; /* 0x15a34: [:dv] parameters, then list listall save */
extern const char *const dv_units[4]; /* 0x15a24 */
extern const int16_t sex_hs_delta[2], sex_f45_q12[2]; /* 0x15bf6, 0x15bfa */
extern const uint16_t sym_flags[256]; /* 0x192e8: symbol code | flags, 0x4000 = pseudo-phoneme */
#endif
