/* GENERATED by decomp/scripts/gen_tx_rom.py from the v1.8 ROM, kept as source (the build does not need the ROM).
 * The text pipeline's ROM data as named, typed tables (REFERENCE.md s13 item 15); ROM addresses in comments. */
#ifndef TX_ROM_H
#define TX_ROM_H
#include <stddef.h>
#include <stdint.h>

extern const char readin_escape[7];
extern const char readin_control[8];
extern const char readin_long_fmt[34];
extern const char spdef_overflow_fmt[29];
extern const char pvalue_bug_fmt[40];
extern const char newclause_size_fmt[41];
extern const char log_dv[4];
extern const char log_fmt[3];
extern const char out_illegal_fmt[32];
extern const char out_long_fmt[33];
extern const char outn_illegal_fmt[31];
extern const char outn_long_fmt[16];
extern const char no_spell_fmt[28];
extern const char dict_illegal_suffix[15];
extern const char bad_dur_fmt[21];
extern const char dur_stop[5];
extern const char sym_value_fmt[3];
extern const char sym_end_pseudo[2];
extern const char sym_end_values[2];
extern const char sym_bad_fmt[8];
extern const char sym_name_fmt[3];
extern const char illegal_phoneme_fmt[22];
extern const char s_one[4];
extern const char s_zero_digit[2];
extern const char s_zero_money[2];
extern const char s_times_ten[17];
extern const char s_exp_minus[6];
extern const char s_power[6];
extern const char s_date_comma[2];
extern const char s_date_end[2];
extern const char s_time_comma1[2];
extern const char s_time_comma2[2];
extern const char s_time_end[2];
extern const char s_dollars[8];
extern const char s_dollar[7];
extern const char s_dollar_sign[2];
extern const char s_plus[5];
extern const char s_minus[6];
extern const char s_point[6];
extern const char s_oh_fraction[3];
extern const char s_zero[5];
extern const char s_dollars_and[12];
extern const char s_dollar_and[11];
extern const char s_no_cents[9];
extern const char s_cent[5];
extern const char s_cents[6];
extern const char s_percent[8];
extern const char s_group_pause[2];
extern const char s_comma_pause[2];
extern const char s_oh_leading[3];
extern const char s_three_zeros[4];
extern const char s_thousand[9];
extern const char s_hundred_year[8];
extern const char s_oh_year[3];
extern const char s_hundred[8];
extern const char s_ty[3];
extern const char s_tieth[6];
extern const char s_tieths[7];
extern const char s_ty_hyphen[4];
extern const char s_over[5];
extern const char s_half[5];
extern const char s_halves[7];
extern const char s_s[2];
extern const char s_empty[1];
extern const char s_th[3];
extern const char s_ths[4];
extern const int8_t readin_class_tab[256]; /* 0x12d10: clause_readin's class of each character */
#define readin_class (readin_class_tab + 1)   /* index -1 .. 0xfe */
extern const int8_t char_class_tab[256]; /* 0x13a1c: the word layer's character classes */
#define char_class (char_class_tab + 128)     /* 0x13a9c; index -128 .. 127 */
extern const uint8_t ctype_tab[128]; /* 0x1d354: the C library's _ctype */
extern const int8_t punct_syms[31]; /* 0x13a58: emit_punctuation_symbol: the clause_putsym symbol of each character 0x21-0x3f */
extern const int8_t dash_syms[7]; /* 0x13a78: spell_chars: a spelled - ("dash" and a word boundary), NUL-ended */
extern const int8_t lts_ascii_map[128]; /* 0x13b48: lts_rule_engine: ASCII -> LTS code (-1 = none) */
extern const int16_t asky_codes[95]; /* 0x19224: DT_MODE ASKY, the symbol of each character 0x20-0x7e (asky_codes[c - 0x20]; 0xff = none) */
extern const int8_t ph_letter_class[95]; /* 0x196a4: lookup_phoneme: letter class of each character 0x20-0x7e (ph_letter_class[c - 0x20]) */
typedef struct { char ascii; int8_t pad; const char *name; uint16_t code; } tx_sym_t;   /* 8 bytes in the ROM */
extern const tx_sym_t sym_table[121]; /* 0x192e2: per symbol code {1-character name, 0, name, code | flags (0x4000 = takes a value)}; [119] ends the list (NULL name); [120] is the ROM overlap, see tx_rom.c */
extern const int16_t sym_max; /* 0x196a2: the highest code phoneme_name knows (120) */
extern const int8_t tail_ly[3];
extern const int8_t tail_ing[3];
extern const int8_t tail_z[2];
extern const int8_t tail_s[2];
extern const int8_t tail_ix_z[3];
extern const int8_t tail_d[2];
extern const int8_t tail_ix_d[3];
extern const int8_t tail_t[2];
extern const int8_t *const dict_tails[9]; /* 0x13b34: the tail each suffix code adds (NULL = none); entries 5-8 are the first bytes of lts_ascii_map */
extern const uint32_t lts_class_masks[31]; /* 0x13c04: feature-class masks */
extern const uint32_t lts_code_features[100]; /* 0x13c80: feature bits of each LTS/phoneme code */
typedef struct { const uint8_t *pattern; int32_t cls; } num_pattern_t;
extern const num_pattern_t pat_number[26]; /* 0x12e56: {number pattern, class}, NULL-ended */
extern const num_pattern_t pat_money[10]; /* 0x12f26: {number pattern, class}, NULL-ended */
extern const char *const num_punct_words[6]; /* 0x12f76: the words for * + , - . / in a digit string (unreachable in v1.8) */
extern const char *const num_months[13]; /* 0x12f8e: "janJanuary": a 3-letter key, then the name, NULL-ended */
extern const char *const num_scales[23]; /* 0x12fc2: "zillion" "thousand" "million" ... "vigintillion", NULL-ended */
extern const char *const num_ones[20]; /* 0x1301e: "zero" ... "nineteen" */
extern const char *const num_ordinals[13]; /* 0x1306e: "zeroth" ... "twelvth" (sic) */
extern const char *const num_tens[8]; /* 0x130a2: "twen" "thir" "for" ... "nine" */
extern const char *const num_units[40]; /* 0x130c2: unit abbreviations: key, singular, plural ("cm\0centimeter\0centimeters"), NULL-ended */

/* the LTS rules (tx_rom_lts.c) */
extern const int8_t lts_rules[6355]; /* 0x13e10: 373 rule records, byte streams; rule n is at the running offset off = -1 + delta[0] + ... + delta[n], its fields from lts_rules[off + 1] on; the last byte is read ahead only */
extern const int16_t lts_rule_deltas[374]; /* 0x156e2: byte length of the previous rule record */
extern const int16_t lts_rule_count; /* 0x159d2: 373 */

/* the built-in dictionary (tx_rom_dict.c; REFERENCE s15.25) */
typedef struct { const int8_t *chars; const int16_t *links; const uint8_t *prons; } dict_root_t;
extern const int16_t dict_first, dict_last; /* 0x20000, 0x20002: the lowest and highest first character */
extern const dict_root_t dict_root[91]; /* 0x20004: per first character: its node's character list, the link words at the same index, the base of its pronunciations (NULL = none) */
extern const int8_t dict_chars[26164]; /* 0x20448: the character lists (bit 7 = the last in its node) */
extern const int16_t dict_links[26163]; /* 0x26a7c: per character, the distance to the child node, or with bit 15 a pronunciation offset */
extern const uint8_t dict_prons[51104]; /* 0x336e2: pronunciations, symbol codes, bit 7 on the last; then the build date "11Oct83" */

#endif
