/* GENERATED by decomp/scripts/gen_tx_rom.py from the v1.8 ROM, kept as source. The text pipeline's tables. */
#include "tx_rom.h"

const char readin_escape[7] = "escape"; /* 0x12d96: clause_readin: said for an ESC */
const char readin_control[8] = "control"; /* 0x12d9d: clause_readin: said before a control character's letter */
const char readin_long_fmt[34] = "long word at clause readin: \"%s\"\n"; /* 0x12da5: clause_readin: log_debug format for a word cut at 79 characters */
const char spdef_overflow_fmt[29] = "spdef overflow (%d entries)\n"; /* 0x12dc8: clause_putsym: [:...] text overflowing a clause */
const char pvalue_bug_fmt[40] = "BUG: phone 0x%x has value, no pvalue[]\n"; /* 0x12de5: clause_putsym: a symbol with values but no values */
const char newclause_size_fmt[41] = "bug: newclause message size %d > max %d\n"; /* 0x12e0d: newclause: message too long */
const char log_dv[4] = ":dv"; /* 0x12e40: log_clause: the prefix of [:...] text */
const char log_fmt[3] = "%s"; /* 0x12e44: log_clause: the format of each symbol */
const char out_illegal_fmt[32] = "Illegal character %d. in out()\n"; /* 0x139e7: out: an illegal character */
const char out_long_fmt[33] = "Long word in number output \"%s\"\n"; /* 0x13a07: out: a word too long */
const char outn_illegal_fmt[31] = "Illegal character %o in out()\n"; /* 0x13a28: outn: an illegal character */
const char outn_long_fmt[16] = "Long word \"%s\"\n"; /* 0x13a47: outn: a word too long */
const char no_spell_fmt[28] = "no spell for '%c' %d. 0x%x\n"; /* 0x13a7f: spell_char: no spelling */
const char dict_illegal_suffix[15] = "Illegal suffix"; /* 0x13b58: pronounce_dictionary_word: panic text (the bytes are also lts_ascii_map[0x10..0x1e]) */
const char bad_dur_fmt[21] = "bad <dur,f0> format\n"; /* 0x191f2: parse_phoneme: a bad <dur,f0> */
const char dur_stop[5] = ">;]\n"; /* 0x19207: parse_phoneme: where it resumes after a bad <dur,f0> */
const char sym_value_fmt[3] = "%u"; /* 0x1920c: phoneme_name: a value */
const char sym_end_pseudo[2] = " "; /* 0x1920f: phoneme_name: after the value of a 0x4000 symbol */
const char sym_end_values[2] = ">"; /* 0x19211: phoneme_name: after the values of a phoneme */
const char sym_bad_fmt[8] = "{?%d.?}"; /* 0x19213: phoneme_name: a code beyond the table */
const char sym_name_fmt[3] = "%s"; /* 0x1921b: phoneme_name: a name */
const char illegal_phoneme_fmt[22] = "Illegal phoneme \"%s\"\n"; /* 0x1984b: lookup_phoneme: an illegal name */
const char s_one[4] = "one"; /* 0x13905: "one", the numerator of 1/n */
const char s_zero_digit[2] = "0"; /* 0x13909: "0" */
const char s_zero_money[2] = "0"; /* 0x1390b: "0" */
const char s_times_ten[17] = "times ten to the"; /* 0x1390d */
const char s_exp_minus[6] = "minus"; /* 0x1391e */
const char s_power[6] = "power"; /* 0x13924 */
const char s_date_comma[2] = ","; /* 0x1392a: after the day */
const char s_date_end[2] = ","; /* 0x1392c: after a date */
const char s_time_comma1[2] = ","; /* 0x1392e: after the hours */
const char s_time_comma2[2] = ","; /* 0x13930: after the minutes */
const char s_time_end[2] = ","; /* 0x13932: after a time */
const char s_dollars[8] = "dollars"; /* 0x13934 */
const char s_dollar[7] = "dollar"; /* 0x1393c */
const char s_dollar_sign[2] = "$"; /* 0x13943 */
const char s_plus[5] = "plus"; /* 0x13945 */
const char s_minus[6] = "minus"; /* 0x1394a */
const char s_point[6] = "point"; /* 0x13950 */
const char s_oh_fraction[3] = "oh"; /* 0x13956 */
const char s_zero[5] = "zero"; /* 0x13959 */
const char s_dollars_and[12] = "dollars and"; /* 0x1395e */
const char s_dollar_and[11] = "dollar and"; /* 0x1396a */
const char s_no_cents[9] = "no cents"; /* 0x13975 */
const char s_cent[5] = "cent"; /* 0x1397e */
const char s_cents[6] = "cents"; /* 0x13983 */
const char s_percent[8] = "percent"; /* 0x13989 */
const char s_group_pause[2] = ","; /* 0x13991: between groups of three digits */
const char s_comma_pause[2] = ","; /* 0x13993: for a comma in a digit string */
const char s_oh_leading[3] = "oh"; /* 0x13995 */
const char s_three_zeros[4] = "000"; /* 0x13998 */
const char s_thousand[9] = "thousand"; /* 0x1399c */
const char s_hundred_year[8] = "hundred"; /* 0x139a5 */
const char s_oh_year[3] = "oh"; /* 0x139ad */
const char s_hundred[8] = "hundred"; /* 0x139b0 */
const char s_ty[3] = "ty"; /* 0x139b8 */
const char s_tieth[6] = "tieth"; /* 0x139bb */
const char s_tieths[7] = "tieths"; /* 0x139c1 */
const char s_ty_hyphen[4] = "ty-"; /* 0x139c8 */
const char s_over[5] = "over"; /* 0x139cc */
const char s_half[5] = "half"; /* 0x139d1 */
const char s_halves[7] = "halves"; /* 0x139d6 */
const char s_s[2] = "s"; /* 0x139dd */
const char s_empty[1] = ""; /* 0x139df */
const char s_th[3] = "th"; /* 0x139e0 */
const char s_ths[4] = "ths"; /* 0x139e3 */
/* 0x12d10-0x12e10: clause_readin's class of each character; readin_class[c] for c = -1 (the end of the text) to 0x7f is the table; 0x80-0xfe would read the strings after it (never: bit 7 is stripped before the text pipe). Bits 0-1 overstrike rank, 2-3 the action (4 control, 8 store, 0xc spoken as "control X"), 0x10 , ! ? ., 0x20 line end, 0x40 end of text, 0x80 blank */
const int8_t readin_class_tab[256] = {
    -32, -32, 12, 4, 4, 12, 12, 12, 12, 4, -124, -96, -32, -96, -96, 4,  /* 12d10 */
    4, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,  /* 12d20 */
    12, -124, 25, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 25, 9, 25,  /* 12d30 */
    9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9,  /* 12d40 */
    25, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  /* 12d50 */
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 4, 9, 4, 9,  /* 12d60 */
    8, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  /* 12d70 */
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9,  /* 12d80 */
    -32, 0, 0, 19, 0, 30, 101, 115, 99, 97, 112, 101, 0, 99, 111, 110,  /* 12d90 */
    116, 114, 111, 108, 0, 108, 111, 110, 103, 32, 119, 111, 114, 100, 32, 97,  /* 12da0 */
    116, 32, 99, 108, 97, 117, 115, 101, 32, 114, 101, 97, 100, 105, 110, 58,  /* 12db0 */
    32, 34, 37, 115, 34, 10, 0, 0, 115, 112, 100, 101, 102, 32, 111, 118,  /* 12dc0 */
    101, 114, 102, 108, 111, 119, 32, 40, 37, 100, 32, 101, 110, 116, 114, 105,  /* 12dd0 */
    101, 115, 41, 10, 0, 66, 85, 71, 58, 32, 112, 104, 111, 110, 101, 32,  /* 12de0 */
    48, 120, 37, 120, 32, 104, 97, 115, 32, 118, 97, 108, 117, 101, 44, 32,  /* 12df0 */
    110, 111, 32, 112, 118, 97, 108, 117, 101, 91, 93, 10, 0, 98, 117, 103,  /* 12e00 */
};
/* 0x13a1c-0x13b1c: the word layer's character classes; char_class[c] for a signed char c: 0 to 0x7f is the table proper (0x13a9c), -128 to -1 read the bytes before it (strings, never reached: bit 7 is stripped). Bits 0x01 opening and 0x02 closing punctuation, 0x04 vowel letter, 0x08 small, 0x10 capital, 0x20 clause mark, 0x40 digit, 0x80 consonant letter */
const int8_t char_class_tab[256] = {
    117, 116, 112, 117, 116, 32, 34, 37, 115, 34, 10, 0, 73, 108, 108, 101,  /* 13a1c */
    103, 97, 108, 32, 99, 104, 97, 114, 97, 99, 116, 101, 114, 32, 37, 111,  /* 13a2c */
    32, 105, 110, 32, 111, 117, 116, 40, 41, 10, 0, 76, 111, 110, 103, 32,  /* 13a3c */
    119, 111, 114, 100, 32, 34, 37, 115, 34, 10, 0, 0, 67, 0, 0, 0,  /* 13a4c */
    0, 0, 0, 0, 0, 0, 0, 66, 0, 69, 0, 0, 0, 0, 0, 0,  /* 13a5c */
    0, 0, 0, 0, 0, 66, 66, 0, 0, 0, 68, 0, 48, 57, 5, 43,  /* 13a6c */
    62, 0, 0, 110, 111, 32, 115, 112, 101, 108, 108, 32, 102, 111, 114, 32,  /* 13a7c */
    39, 37, 99, 39, 32, 37, 100, 46, 32, 48, 120, 37, 120, 10, 0, 0,  /* 13a8c */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  /* 13a9c */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  /* 13aac */
    0, 34, 3, 0, 0, 0, 0, 3, 1, 2, 0, 0, 34, 0, 34, 0,  /* 13abc */
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 34, 34, 0, 0, 0, 34,  /* 13acc */
    0, 20, -112, -112, -112, 20, -112, -112, -112, 20, -112, -112, -112, -112, -112, 20,  /* 13adc */
    -112, -112, -112, -112, -112, 20, -112, -112, -112, 16, -112, 1, 0, 2, 0, 0,  /* 13aec */
    1, 12, -120, -120, -120, 12, -120, -120, -120, 12, -120, -120, -120, -120, -120, 12,  /* 13afc */
    -120, -120, -120, -120, -120, 12, -120, -120, -120, 8, -120, 1, 0, 2, 0, 0,  /* 13b0c */
};
/* 0x1d354-0x1d3d4: the C library's _ctype, indexed by c & 0x7f: 1 upper, 2 lower, 4 digit, 8 space, 0x10 punct, 0x20 control, 0x40 hex, 0x80 blank */
const uint8_t ctype_tab[128] = {
    0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x28, 0x28, 0x28, 0x28, 0x28, 0x20, 0x20,  /* 1d354 */
    0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,  /* 1d364 */
    0x88, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10,  /* 1d374 */
    0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10,  /* 1d384 */
    0x10, 0x41, 0x41, 0x41, 0x41, 0x41, 0x41, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,  /* 1d394 */
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x10, 0x10, 0x10, 0x10, 0x10,  /* 1d3a4 */
    0x10, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,  /* 1d3b4 */
    0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x10, 0x10, 0x10, 0x10, 0x20,  /* 1d3c4 */
};
/* 0x13a58-0x13a77: emit_punctuation_symbol: the clause_putsym symbol of each character 0x21-0x3f */
const int8_t punct_syms[31] = {
    67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 0, 69, 0, 0,  /* 13a58 */
    0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 66, 0, 0, 0, 68,  /* 13a68 */
};
/* 0x13a78-0x13a7f: spell_chars: a spelled - ("dash" and a word boundary), NUL-ended */
const int8_t dash_syms[7] = {
    48, 57, 5, 43, 62, 0, 0,  /* 13a78 */
};
/* 0x13b48-0x13bc8: lts_rule_engine: ASCII -> LTS code (-1 = none); entries 0x00-0x0f are the last four suffix-tail pointers and 0x10-0x1e the string "Illegal suffix" (the ROM overlaps them); a word never holds those characters */
const int8_t lts_ascii_map[128] = {
    0, 1, 59, 40, 0, 1, 59, 44, 0, 1, 59, 46, 0, 1, 59, 50,  /* 13b48 */
    73, 108, 108, 101, 103, 97, 108, 32, 115, 117, 102, 102, 105, 120, 0, 0,  /* 13b58 */
    62, 67, 59, -1, -1, -1, -1, 57, 63, 64, 61, -1, -1, -1, -1, -1,  /* 13b68 */
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  /* 13b78 */
    -1, 70, 46, 77, 48, 71, 37, 50, 75, 72, 78, 49, 27, 31, 32, 73,  /* 13b88 */
    45, 79, 26, 41, 47, 74, 38, 24, 76, 25, 42, 65, -1, 66, -1, -1,  /* 13b98 */
    58, 70, 46, 77, 48, 71, 37, 50, 75, 72, 78, 49, 27, 31, 32, 73,  /* 13ba8 */
    45, 79, 26, 41, 47, 74, 38, 24, 76, 25, 42, -1, -1, -1, 81, 0,  /* 13bb8 */
};
/* 0x19224-0x192e0: lookup_phoneme in DT_MODE ASKY: the symbol code of each character 0x20-0x7e (0xff = none) */
const int16_t asky_codes[95] = {
    0x3e, 0x43, 0x3b, 0x38, 0xff, 0xff, 0x33, 0x39, 0x3f, 0x40, 0x3d, 0xff, 0x42, 0x3c, 0x45, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x44,
    0x05, 0x07, 0x6c, 0x36, 0x28, 0x04, 0x6e, 0x21, 0x6d, 0x02, 0x37, 0x70, 0x22, 0x23, 0x24, 0x0c,
    0x6b, 0x34, 0x0f, 0x2b, 0x27, 0x0d, 0x73, 0x08, 0xff, 0x10, 0x2c, 0x41, 0xff, 0xff, 0x09, 0x00,
    0x3a, 0x06, 0x2e, 0x0a, 0x30, 0x03, 0x25, 0x32, 0x1c, 0x01, 0xff, 0x31, 0x1b, 0x1f, 0x20, 0x0b,
    0x2d, 0x35, 0x1a, 0x29, 0x2f, 0x0e, 0x26, 0x18, 0x11, 0x19, 0x2a, 0xff, 0x12, 0xff, 0xff,
};
/* 0x196a4-0x19703: lookup_phoneme: letter class of each character 0x20-0x7e (ph_letter_class[c - 0x20]); bits 0-1: 2 stands alone, 1 must take a second letter, 3 may; bit 2 can follow a class-1 letter, bit 3 a class-3 one */
const int8_t ph_letter_class[95] = {
    2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0,  /* 196a4 */
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2,  /* 196b4 */
    0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 3, 0, 0, 0, 0, 2,  /* 196c4 */
    0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2,  /* 196d4 */
    2, 5, 3, 3, 3, 5, 3, 3, 15, 5, 3, 3, 7, 7, 7, 5,  /* 196e4 */
    3, 3, 7, 3, 3, 5, 3, 7, 15, 7, 3, 0, 0, 0, 0,  /* 196f4 */
};
/* 0x192e2: the symbol table, per code {1-character name (DT_MODE ASKY), 0, name, code | flags}. Record 119 ends lookup_phoneme's search (NULL name; phoneme_name prints it as ROM address 0, which holds 0: an empty string). Record 120 is what the ROM finds past the table: sym_max (its first word) and ph_letter_class (the rest); its name pointer 0x02020202 reads ROM 0x020202 on the 24-bit bus, inside the dictionary index. */
const tx_sym_t sym_table[121] = {
    { '_', 0, "_", 0x0000 },  /* 0 */
    { 'i', 0, "iy", 0x0001 },  /* 1 */
    { 'I', 0, "ih", 0x0002 },  /* 2 */
    { 'e', 0, "ey", 0x0003 },  /* 3 */
    { 'E', 0, "eh", 0x0004 },  /* 4 */
    { '@', 0, "ae", 0x0005 },  /* 5 */
    { 'a', 0, "aa", 0x0006 },  /* 6 */
    { 'A', 0, "ay", 0x0007 },  /* 7 */
    { 'W', 0, "aw", 0x0008 },  /* 8 */
    { '^', 0, "ah", 0x0009 },  /* 9 */
    { 'c', 0, "ao", 0x000a },  /* 10 */
    { 'o', 0, "ow", 0x000b },  /* 11 */
    { 'O', 0, "oy", 0x000c },  /* 12 */
    { 'U', 0, "uh", 0x000d },  /* 13 */
    { 'u', 0, "uw", 0x000e },  /* 14 */
    { 'R', 0, "rr", 0x000f },  /* 15 */
    { 'Y', 0, "yu", 0x0010 },  /* 16 */
    { 'x', 0, "ax", 0x0011 },  /* 17 */
    { '|', 0, "ix", 0x0012 },  /* 18 */
    { 'i', 0, "ir", 0x0013 },  /* 19 */
    { 'e', 0, "er", 0x0014 },  /* 20 */
    { 'a', 0, "ar", 0x0015 },  /* 21 */
    { 'o', 0, "or", 0x0016 },  /* 22 */
    { 'u', 0, "ur", 0x0017 },  /* 23 */
    { 'w', 0, "w", 0x0018 },  /* 24 */
    { 'y', 0, "y", 0x0019 },  /* 25 */
    { 'r', 0, "r", 0x001a },  /* 26 */
    { 'l', 0, "l", 0x001b },  /* 27 */
    { 'h', 0, "hx", 0x001c },  /* 28 */
    { 'r', 0, "rx", 0x001d },  /* 29 */
    { 'l', 0, "lx", 0x001e },  /* 30 */
    { 'm', 0, "m", 0x001f },  /* 31 */
    { 'n', 0, "n", 0x0020 },  /* 32 */
    { 'G', 0, "nx", 0x0021 },  /* 33 */
    { 'L', 0, "el", 0x0022 },  /* 34 */
    { 'M', 0, "em", 0x0023 },  /* 35 */
    { 'N', 0, "en", 0x0024 },  /* 36 */
    { 'f', 0, "f", 0x0025 },  /* 37 */
    { 'v', 0, "v", 0x0026 },  /* 38 */
    { 'T', 0, "th", 0x0027 },  /* 39 */
    { 'D', 0, "dh", 0x0028 },  /* 40 */
    { 's', 0, "s", 0x0029 },  /* 41 */
    { 'z', 0, "z", 0x002a },  /* 42 */
    { 'S', 0, "sh", 0x002b },  /* 43 */
    { 'Z', 0, "zh", 0x002c },  /* 44 */
    { 'p', 0, "p", 0x002d },  /* 45 */
    { 'b', 0, "b", 0x002e },  /* 46 */
    { 't', 0, "t", 0x002f },  /* 47 */
    { 'd', 0, "d", 0x0030 },  /* 48 */
    { 'k', 0, "k", 0x0031 },  /* 49 */
    { 'g', 0, "g", 0x0032 },  /* 50 */
    { '&', 0, "dx", 0x0033 },  /* 51 */
    { 'Q', 0, "tx", 0x0034 },  /* 52 */
    { 'q', 0, "q", 0x0035 },  /* 53 */
    { 'C', 0, "ch", 0x0036 },  /* 54 */
    { 'J', 0, "jh", 0x0037 },  /* 55 */
    { '#', 0, "#", 0x0038 },  /* 56 */
    { '\'', 0, "'", 0x0039 },  /* 57 */
    { '`', 0, "`", 0x003a },  /* 58 */
    { '"', 0, "\"", 0x003b },  /* 59 */
    { '-', 0, "-", 0x003c },  /* 60 */
    { '*', 0, "*", 0x003d },  /* 61 */
    { ' ', 0, " ", 0x003e },  /* 62 */
    { '(', 0, "(", 0x003f },  /* 63 */
    { ')', 0, ")", 0x0040 },  /* 64 */
    { '[', 0, "[", 0x0041 },  /* 65 */
    { ',', 0, ",", 0x0042 },  /* 66 */
    { '!', 0, "!", 0x0043 },  /* 67 */
    { '?', 0, "?", 0x0044 },  /* 68 */
    { '.', 0, ".", 0x0045 },  /* 69 */
    { ' ', 0, "A", 0x0046 },  /* 70 */
    { ' ', 0, "E", 0x0047 },  /* 71 */
    { ' ', 0, "I", 0x0048 },  /* 72 */
    { ' ', 0, "O", 0x0049 },  /* 73 */
    { ' ', 0, "U", 0x004a },  /* 74 */
    { ' ', 0, "H", 0x001c },  /* 75 */
    { ' ', 0, "X", 0x004c },  /* 76 */
    { ' ', 0, "C", 0x004d },  /* 77 */
    { ' ', 0, "J", 0x004e },  /* 78 */
    { ' ', 0, "Q", 0x004f },  /* 79 */
    { ' ', 0, "@", 0x0050 },  /* 80 */
    { ' ', 0, "~~", 0x0051 },  /* 81 */
    { ' ', 0, ":::", 0x0052 },  /* 82 */
    { ' ', 0, ":++", 0x0053 },  /* 83 */
    { ' ', 0, ":--", 0x0054 },  /* 84 */
    { ' ', 0, " ", 0x0055 },  /* 85 */
    { ' ', 0, " ", 0x0056 },  /* 86 */
    { ' ', 0, ":==", 0x0057 },  /* 87 */
    { ' ', 0, ":$$", 0x0058 },  /* 88 */
    { ' ', 0, "0", 0x0059 },  /* 89 */
    { ' ', 0, "1", 0x005a },  /* 90 */
    { ' ', 0, "2", 0x005b },  /* 91 */
    { ' ', 0, "3", 0x005c },  /* 92 */
    { ' ', 0, "4", 0x005d },  /* 93 */
    { ' ', 0, "5", 0x005e },  /* 94 */
    { ' ', 0, "6", 0x005f },  /* 95 */
    { ' ', 0, "7", 0x0060 },  /* 96 */
    { ' ', 0, "8", 0x0061 },  /* 97 */
    { ' ', 0, "9", 0x0062 },  /* 98 */
    { ' ', 0, ":##", 0x0063 },  /* 99 */
    { ' ', 0, ":vo", 0x4064 },  /* 100 */
    { ' ', 0, ":ra", 0x4065 },  /* 101 */
    { ' ', 0, ":in", 0x4066 },  /* 102 */
    { ' ', 0, ":re", 0x4067 },  /* 103 */
    { ' ', 0, " : ", 0x4068 },  /* 104 */
    { ' ', 0, ":pp", 0x4069 },  /* 105 */
    { ' ', 0, ":cp", 0x406a },  /* 106 */
    { 'P', 0, ":np", 0x006b },  /* 107 */
    { 'B', 0, ":nb", 0x006c },  /* 108 */
    { 'H', 0, ":nh", 0x006d },  /* 109 */
    { 'F', 0, ":nf", 0x006e },  /* 110 */
    { '1', 0, ":nd", 0x006f },  /* 111 */
    { 'K', 0, ":nk", 0x0070 },  /* 112 */
    { '3', 0, ":nu", 0x0071 },  /* 113 */
    { '2', 0, ":nr", 0x0072 },  /* 114 */
    { 'V', 0, ":nv", 0x0073 },  /* 115 */
    { ':', 0, ":se", 0x4074 },  /* 116 */
    { '~', 0, ":dr", 0x4075 },  /* 117 */
    { ' ', 0, ":db", 0x4076 },  /* 118 */
    { 0, 0, NULL, 0xffff },  /* 119 */
    { 0, 120, "n^", 0x0200 },  /* 120 */
};
const int16_t sym_max = 120;
const int8_t tail_ly[3] = { 27, 1, 0 };  /* 0x13b1c */
const int8_t tail_ing[3] = { 2, 33, 0 };  /* 0x13b20 */
const int8_t tail_z[2] = { 42, 0 };  /* 0x13b24 */
const int8_t tail_s[2] = { 41, 0 };  /* 0x13b26 */
const int8_t tail_ix_z[3] = { 18, 42, 0 };  /* 0x13b28 */
const int8_t tail_d[2] = { 48, 0 };  /* 0x13b2c */
const int8_t tail_ix_d[3] = { 18, 48, 0 };  /* 0x13b2e */
const int8_t tail_t[2] = { 47, 0 };  /* 0x13b32 */
/* 0x13b34: the symbols each suffix code adds after a dictionary word (NULL = none); entries 5-8 overlap lts_ascii_map in the ROM */
const int8_t *const dict_tails[9] = { NULL, tail_ly, tail_ing, tail_z, tail_s, tail_ix_z, tail_d, tail_ix_d, tail_t };
/* 0x13c04: feature-class masks */
const uint32_t lts_class_masks[31] = {
    0x00000000, 0x00080000, 0x00100000, 0x04000000, 0x00000008, 0x00000010,
    0x00000020, 0x00000040, 0x00000080, 0x00000100, 0x00000200, 0x00000400,
    0x00000800, 0x00001000, 0x00002000, 0x00004000, 0x00008000, 0x00010000,
    0x00020000, 0x00040000, 0x00000001, 0x00000002, 0x00200000, 0x00400000,
    0x00800000, 0x01000000, 0x02000000, 0x00000004, 0x08000000, 0x10000000,
    0x20000000,
};
/* 0x13c80: feature bits of each LTS/phoneme code */
const uint32_t lts_code_features[100] = {
    0x00060000, 0x0c090a18, 0x08090a18, 0x0c090a08, 0x08090a00, 0x08090a20,
    0x08090a60, 0x0c098a60, 0x0c098a60, 0x08090a60, 0x08090ac0, 0x0c090ac0,
    0x0c098ac0, 0x08090ad0, 0x0c090ad0, 0x0c090a00, 0x0c090ad0, 0x08090a60,
    0x08090a18, 0x0c090a18, 0x0c090a00, 0x08090a60, 0x0c090ac0, 0x0c090ad0,
    0x10191b00, 0x10193a08, 0x10392a00, 0x30393a00, 0x10110b00, 0x10392a00,
    0x10393a00, 0x10111c00, 0x10113c00, 0x10110d00, 0x08293a00, 0x08091e00,
    0x08093e00, 0x10115300, 0x30115b00, 0x10117300, 0x10117b00, 0x30517300,
    0x30517b00, 0x10516300, 0x10516b00, 0x10111100, 0x10111900, 0x10113100,
    0x10113900, 0x10110100, 0x30110900, 0x00000000, 0x00000000, 0x10110000,
    0x10516300, 0x10516b00, 0x00000000, 0x00000000, 0x00000000, 0x00060000,
    0x00000000, 0x00060000, 0x00060000, 0x00060000, 0x00060000, 0x00060000,
    0x00060000, 0x00060000, 0x00060000, 0x00060000, 0x08090800, 0x08090808,
    0x08090808, 0x08090800, 0x08090800, 0x10110000, 0x10110000, 0x30110000,
    0x10110000, 0x10110000, 0x02060000, 0x02060000, 0x00060000, 0x02040004,
    0x02020004, 0x00000000, 0x00000000, 0x00060000, 0x00060000, 0x02000000,
    0x02000000, 0x02000000, 0x02000000, 0x02000000, 0x02000000, 0x02000000,
    0x02000000, 0x02000000, 0x02000000, 0x00060000,
};
const uint8_t pat_13162[12] = { 0x02, 0x05, 0x04, 0x0f, 0x31, 0x39, 0x0b, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_1316e[8] = { 0x02, 0x08, 0x01, 0x30, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13176[11] = { 0x02, 0x08, 0x0e, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13181[16] = { 0x02, 0x08, 0x0e, 0x10, 0x01, 0x2e, 0x07, 0x0b, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13191[16] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x2e, 0x08, 0x0b, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131a1[11] = { 0x02, 0x08, 0x0e, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131ac[16] = { 0x02, 0x01, 0x31, 0x01, 0x2f, 0x0b, 0x09, 0x0b, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131bc[18] = { 0x02, 0x01, 0x31, 0x01, 0x2f, 0x01, 0x31, 0x01, 0x30, 0x01, 0x30, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131ce[18] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x2f, 0x0b, 0x09, 0x0b, 0x10, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131e0[20] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x2f, 0x01, 0x31, 0x01, 0x30, 0x01, 0x30, 0x09, 0x01, 0x25, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_131f4[17] = { 0x02, 0x07, 0x0e, 0x10, 0x05, 0x05, 0x30, 0x0f, 0x34, 0x39, 0x01, 0x74, 0x01, 0x68, 0x03, 0x10, 0x00 };
const uint8_t pat_13205[13] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x31, 0x01, 0x73, 0x01, 0x74, 0x03, 0x10, 0x00 };
const uint8_t pat_13212[13] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x32, 0x01, 0x6e, 0x01, 0x64, 0x03, 0x10, 0x00 };
const uint8_t pat_1321f[13] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x33, 0x01, 0x72, 0x01, 0x64, 0x03, 0x10, 0x00 };
const uint8_t pat_1322c[14] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x31, 0x0b, 0x01, 0x74, 0x01, 0x68, 0x03, 0x10, 0x00 };
const uint8_t pat_1323a[22] = { 0x02, 0x08, 0x05, 0x05, 0x2e, 0x0f, 0x30, 0x39, 0x10, 0x01, 0x65, 0x05, 0x03, 0x2b, 0x2d, 0x0b, 0x09, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13250[18] = { 0x02, 0x08, 0x05, 0x05, 0x2e, 0x0f, 0x30, 0x39, 0x10, 0x01, 0x65, 0x0b, 0x09, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13262[12] = { 0x02, 0x08, 0x05, 0x05, 0x2e, 0x0f, 0x30, 0x39, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_1326e[17] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x2d, 0x0a, 0x0a, 0x0a, 0x01, 0x2d, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_1327f[13] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x2d, 0x0a, 0x0a, 0x0a, 0x03, 0x10, 0x00 };
const uint8_t pat_1328c[19] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x2d, 0x0a, 0x0a, 0x0a, 0x01, 0x2d, 0x0b, 0x0b, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_1329f[20] = { 0x02, 0x0b, 0x0b, 0x01, 0x3a, 0x0b, 0x0b, 0x01, 0x3a, 0x0b, 0x0b, 0x01, 0x2e, 0x0b, 0x08, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_132b3[19] = { 0x02, 0x0b, 0x01, 0x3a, 0x0b, 0x0b, 0x01, 0x3a, 0x0b, 0x0b, 0x01, 0x2e, 0x0b, 0x08, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_132c6[16] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x3a, 0x0b, 0x0b, 0x01, 0x3a, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_132d6[12] = { 0x02, 0x0b, 0x09, 0x0b, 0x10, 0x01, 0x3a, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_132e2[10] = { 0x02, 0x01, 0x31, 0x01, 0x2e, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_132ec[10] = { 0x02, 0x01, 0x2e, 0x01, 0x30, 0x01, 0x31, 0x03, 0x10, 0x00 };
const uint8_t pat_132f6[11] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x2e, 0x0b, 0x0b, 0x03, 0x10, 0x00 };
const uint8_t pat_13301[6] = { 0x02, 0x01, 0x31, 0x03, 0x10, 0x00 };
const uint8_t pat_13307[8] = { 0x02, 0x08, 0x01, 0x30, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_1330f[7] = { 0x02, 0x08, 0x0e, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13316[12] = { 0x02, 0x07, 0x0e, 0x10, 0x01, 0x2e, 0x08, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_13322[12] = { 0x02, 0x08, 0x0e, 0x10, 0x01, 0x2e, 0x07, 0x0b, 0x10, 0x03, 0x10, 0x00 };
const uint8_t pat_1332e[7] = { 0x02, 0x08, 0x0e, 0x10, 0x03, 0x10, 0x00 };
/* 0x12e56: classify_number's {pattern, class} list (patterns: REFERENCE s15.27), NULL-ended */
const num_pattern_t pat_number[26] = {
    { pat_13162, 7 },
    { pat_1316e, 8 },
    { pat_13176, 9 },
    { pat_13181, 9 },
    { pat_13191, 9 },
    { pat_131a1, 9 },
    { pat_131ac, 10 },
    { pat_131bc, 10 },
    { pat_131ce, 11 },
    { pat_131e0, 11 },
    { pat_131f4, 12 },
    { pat_13205, 12 },
    { pat_13212, 12 },
    { pat_1321f, 12 },
    { pat_1322c, 12 },
    { pat_1323a, 13 },
    { pat_13250, 13 },
    { pat_13262, 13 },
    { pat_1326e, 14 },
    { pat_1327f, 14 },
    { pat_1328c, 15 },
    { pat_1329f, 16 },
    { pat_132b3, 16 },
    { pat_132c6, 16 },
    { pat_132d6, 16 },
    { NULL, 0 }
};
/* 0x12f26: classify_number's {pattern, class} list (patterns: REFERENCE s15.27), NULL-ended */
const num_pattern_t pat_money[10] = {
    { pat_132e2, 2 },
    { pat_132ec, 2 },
    { pat_132f6, 3 },
    { pat_13301, 4 },
    { pat_13307, 5 },
    { pat_1330f, 6 },
    { pat_13316, 6 },
    { pat_13322, 6 },
    { pat_1332e, 6 },
    { NULL, 0 }
};
/* 0x12f76: the words for * + , - . / in a digit string (unreachable in v1.8) */
const char *const num_punct_words[6] = {
    "times",
    "plus",
    "comma",
    "minus",
    "dot",
    "over",
};
/* 0x12f8e: "janJanuary": a 3-letter key, then the name */
const char *const num_months[13] = {
    "janJanuary",
    "febFebruary",
    "marMarch",
    "aprApril",
    "mayMay",
    "junJune",
    "julJuly",
    "augAugust",
    "sepSeptember",
    "octOctober",
    "novNovember",
    "decDecember",
    NULL,
};
/* 0x12fc2: "zillion" "thousand" "million" ... "vigintillion" */
const char *const num_scales[23] = {
    "zillion",
    "thousand",
    "million",
    "billion",
    "trillion",
    "quadrillion",
    "quintillion",
    "sextillion",
    "septillion",
    "octillion",
    "nonillion",
    "decillion",
    "undecillion",
    "duodecillion",
    "tredecillion",
    "quattuordecillion",
    "quindecillion",
    "sexdecillion",
    "septdecillion",
    "octodecillion",
    "novemdecillion",
    "vigintillion",
    NULL,
};
/* 0x1301e: "zero" ... "nineteen" */
const char *const num_ones[20] = {
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
};
/* 0x1306e: "zeroth" ... "twelvth" (sic) */
const char *const num_ordinals[13] = {
    "zeroth",
    "first",
    "second",
    "third",
    "fourth",
    "fifth",
    "sixth",
    "seventh",
    "eighth",
    "ninth",
    "tenth",
    "eleventh",
    "twelvth",
};
/* 0x130a2: "twen" "thir" "for" ... "nine" */
const char *const num_tens[8] = {
    "twen",
    "thir",
    "for",
    "fif",
    "six",
    "seven",
    "eigh",
    "nine",
};
/* 0x130c2: unit abbreviations: key, singular, plural ("cm\0centimeter\0centimeters") */
const char *const num_units[40] = {
    "m\000meter\000meters",
    "cm\000centimeter\000centimeters",
    "mm\000millimeter\000millimeters",
    "km\000kilometer\000kilometers",
    "in\000inch\000inches",
    "ins\000inches\000inches",
    "ft\000foot\000feet",
    "yd\000yard\000yards",
    "yds\000yards\000yards",
    "mi\000mile\000miles",
    "ha\000hectare\000hectares",
    "sq.in\000square inch\000square inches",
    "sq.ft\000square foot\000square feet",
    "sq.yd\000square yard\000square yards",
    "ml\000milliliter\000milliliters",
    "l\000liter\000liters",
    "tsp\000tea-spoon\000tea-spoons",
    "tsps\000tea-spoons\000tea-spoons",
    "tbsp\000table-spoon\000tablespoons",
    "tbsps\000table-spoons\000tablespoons",
    "qt\000quart\000quarts",
    "gm\000gram\000grams",
    "mg\000milligram\000milligrams",
    "g\000gram\000grams",
    "kg\000kilogram\000kilograms",
    "lb\000pound\000pounds",
    "lbs\000pounds\000pounds",
    "oz\000ounce\000ounces",
    "ozs\000ounces\000ounces",
    "nsec\000nano-second\000nano-seconds",
    "usec\000micro-second\000micro-seconds",
    "msec\000milli-second\000milli-seconds",
    "sec\000second\000seconds",
    "secs\000seconds\000seconds",
    "min\000minute\000minutes",
    "hr\000hour\000hours",
    "deg\000degree\000degrees",
    "kt\000knot\000knots",
    "kts\000knots\000knots",
    NULL,
};
